# Generated by Django 3.1.6 on 2021-02-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('code', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='emailcodeconfirmation',
            name='check',
        ),
    ]
